### ISSUE TITLE
AR camera view

### ISSUE THREAD

**Issue by Natureshadow** [Veripeditus/veripeditus-server#15]
Add a camera view that shows game objects when looking at them.

Design ideas:
- Use flat SVG images for objects for now, i.e. the same as for the map view.
- Scale images according to distance from player, e.g. 95% of screen for directly next to the player, down to 5% for 100m away; hide if they are farther away.
- Images should be 3D transformed when not looking directly at them.

**Comment by Natureshadow** [comment]
@Creeparoo Do we want this working at the next presentation?

**Comment by Creeparoo** [comment]
Yes!

**Comment by Natureshadow** [comment]
@Creeparoo, now that's your own fault for having to fix it ;)!
