### ISSUE TITLE
Enable worlds in frontend and backend

### ISSUE THREAD

**Issue by Natureshadow** [Veripeditus/veripeditus-server#23]
Enable the concept of worlds. This includes:
- Assigning players to worlds in the backend
- Make writing API calls aware of the current world
- Provide world-selection in the web UI

For this, the Player object should be moved to world-context, associated with a server-wide User object.

**Comment by Creeparoo** [comment]
Issue closed.

**Comment by Natureshadow** [comment]
Not finished yet (see issue description).

**Comment by Natureshadow** [comment]
Selecting world in the frontend is not needed for ORR, adding it now woul over-crowd the ugly UI.
