### ISSUE TITLE
Debug mode breaks leaflet on mobile 

### ISSUE THREAD

**Issue by Natureshadow** [Veripeditus/veripeditus-server#41]
The debug mode captures touch events and then tries to handle them as
mouse event, resulting in Leaflet stopping with a message that
.originalEvent is undefined.

**Comment by Creeparoo** [comment]
We tried to reproduce the bug and debugged the code, but we couldn't find a way to let it happen again. We tested if event had a property originalEvent where the bug occured. It was there, on a computer aswell as mobile.
We can't be sure if the bug even occurs on that particular spot or if it occurs on every device.

**Comment by Natureshadow** [comment]
I actually do not see the bug anymore either. I got it at some point on my mobile firefox, but it seemed to happen on a resize event of some kind. Certainly debug mode is not what triggers this bug.
