### ISSUE TITLE
double authentication bug

### ISSUE THREAD

**Issue by Kampfzwerg87** [Veripeditus/veripeditus-server#42]
In Firefox for Android:
After my first authentication via the in game menu the browser pops out a formular for a second authentication.

**Comment by Natureshadow** [comment]
That's because we enforce authentication for everything below `/api` now and moved the image URL to `/api/gameobject/<ID>/image_raw`.

There are two solutions:

 * Enable more fine-grained ACLs server-side
 * Load images through jQuery, which has the credentials

**Comment by Natureshadow** [comment]
Uh, we might need to revisit this at some point, because we might actually want to impose authentication on images…
