### ISSUE TITLE
Basic game data from game module

### ISSUE THREAD

**Issue by Natureshadow** [Veripeditus/veripeditus-server#5]
Decide on and document basic constants that will be part of the game modules (top-level, constants).

We should start with the following:

NAME - Friendly name of the game
VERSION - Version code of the game in this package
DESCRIPTION - Short description of the game

@Creeparoo, feel free to add any constant that you deem necessary ☺!

**Comment by Creeparoo** [comment]
AUTHOR
LICENSE
LANGUAGE

**Comment by Natureshadow** [comment]
LANGUAGE is not a good idea, as we will want to internationalise everything
