### ISSUE TITLE
owned_max is off by one

### ISSUE THREAD

**Issue by Natureshadow** [Veripeditus/veripeditus-server#54]
For some reason, Veripeditus now stops allowing collecting an item if `owned_max -1` items are held.

**Comment by Creeparoo** [comment]
The problem hasn't occured for me yet. It works perfectly fine just as it should.

**Comment by Natureshadow** [comment]
@Creeparoo, please test again, with two different sorts of items with different spawn behaviour. If you find that everything works as expected, please close the issue and labe it as "invalid".

**Comment by Natureshadow** [comment]
Closing as it does not seem reproducible.

**Comment by Natureshadow** [comment]
Got it again, reproducible, with the current test game in master.
