### ISSUE TITLE
Allow spawning at random locations inside a polygon

### ISSUE THREAD

**Issue by Natureshadow** [Veripeditus/veripeditus-server#68]
Allow spawning at random locations inside a polygon, both within an OpenStreetMap area and within a user-defined polygon of coordinates.

**Comment by Natureshadow** [comment]
For OSM, this is kind of a challenge because querying for a polygon that crosses a point is not so straightforward. Maybe it needs changes to OSMAlchemy as well.

**Comment by Creeparoo** [comment]
Works fine with a polygon format ((lat, lon), (lat, lon), (lat, lon), …) aswell as with a rect format ((lat, lon), (lat, lon))
