### ISSUE TITLE
Game objects in camera view are stacked wrongly

### ISSUE THREAD

**Issue by Natureshadow** [Veripeditus/veripeditus-server#80]
The game objects need a z-index representing their distance to the player.

**Comment by Natureshadow** [comment]
@mirabilos Hmm, shouldn't the z-index get bigger when the items get closer? Also, shouldn't it go into the image_div style instead?

**Comment by mirabilos** [comment]
Dominik George dixit:

>@mirabilos Hmm, shouldn't the z-index get bigger when the items get
>closer?

Errp… yes. I blame sleep deprivation and lack of a cidre channel.

>Also, shouldn't it go into the image_div style instead?

Unsure. Maybe, maybe not. Let’s do this when we have an actual test
case.

gn8,
//mirabilos
-- 
18:47⎜<mirabilos:#!/bin/mksh> well channels… you see, I see everything in the
same window anyway      18:48⎜<xpt:#!/bin/mksh> i know, you have some kind of
telnet with automatic pong         18:48⎜<mirabilos:#!/bin/mksh> haha, yes :D
18:49⎜<mirabilos:#!/bin/mksh> though that's more tinyirc – sirc is more comfy
