### ISSUE TITLE
Issues with legal files

### ISSUE THREAD

**Issue by mirabilos** [Veripeditus/veripeditus-server#81]
Short notes, I’ll have to do more review later:

- swap COPYING and LICENSE: LICEN[CS]E is supposed to have the complete licence terms minus extra legal documents, whereas COPYING is a common name{, prefix} for GNU licence documents
- LICENCE must include the proper Creative Commons grants, not the deeds
- in the same vain, several mentioned CC licences are missing the full legal documents for them
- the kangaroo needs attribution (at least Leaflet does provide this) on the map, and likely in the player popup as well

**Comment by mirabilos** [comment]
Also fun: Debian does not permit packages to ship extra licence files, so there *must* be a Debian-specific patch replacing a number of files by a copy of the debian/copyright file…

**Comment by Natureshadow** [comment]
Hehe, yes, I also thought about that just now...

**Comment by Natureshadow** [comment]
>- swap COPYING and LICENSE: LICEN[CS]E is supposed to have the complete
>licence terms minus extra legal documents, whereas COPYING is a common
>name{, prefix} for GNU licence documents

Well, that's opinion-based.

>- in the same vain, several mentioned CC licences are missing the full
>legal documents for them
>- the kangaroo needs attribution (at least Leaflet does provide this)
>on the map, and likely in the player popup as well

We can also just remove all the CC stuff. Dual-licensing our own material is not necessary, and on second look we got a "pick any open source license you like" statement for the kangaroo.

**Comment by mirabilos** [comment]
ad 1: It’s not.

ad 2: If we have a different permit, why not use that instead…

**Comment by Natureshadow** [comment]
Everything done so far; all the SVGs still need correct license RDF tags.
