### ISSUE TITLE
Possibility to have unique items to hand over or drop

### ISSUE THREAD

**Issue by cvwillegen** [Veripeditus/veripeditus-server#85]
It would be nice to have the possibility to create unique items that you can find only one instance of. You would need to drop this at a location or give it to another player.

**Comment by Natureshadow** [comment]
Unique items and handing over are already possible.

Dropping on map could be simplified.

**Comment by Natureshadow** [comment]
Let's call this placing, not dropping, because we already called removing an item dropping.

@Creeparoo, will you implement this, together with all methods and integration necessary?

**Comment by Creeparoo** [comment]
Works.
