### ISSUE TITLE
Requires removal from GitHub (or relicencing)

### ISSUE THREAD

**Issue by mirabilos** [Veripeditus/veripeditus-server#99]
Due to http://www.mirbsd.org/permalinks/wlog-10_e20170301-tg.htm this project must be removed from GitHub in its entirety (including all forks), requires an explicit waiver (which would make merging e.g. external works under CC-BY-* licences impossible), or relicencing.

This also affects the following subprojects, some of which have no issue tracker:
- https://github.com/Veripeditus/game-fosdem17
- https://github.com/Veripeditus/game-verimagica
- https://github.com/Veripeditus/game-ingressio

**Comment by Natureshadow** [comment]
This does not need to be tracked in every single issue tracker.
